AddRemoteEvent("OnOpenGarage", function(player)
    local x, y, z = GetPlayerLocation(player)
    local NearestGarage = GetNearestZone(g_Points, x, y, z)
    CallRemoteEvent(player, "OpenGarage", NearestGarage.id, PlayerData[player].vehicles)
end)